spring:
  datasource:
    url: jdbc:h2:file:./src/main/resources/data/ergo_web_service_db
    driver-class-name: org.h2.Driver
    username: ergo_service
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

